# **Data preprocessing for ML**

In [ ]:
import numpy as np
import pandas as pd
import random
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df=pd.read_csv(r'/content/drive/MyDrive/colab datasets/train.csv')
df

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,accident_risk
0,0,urban,2,0.06,35,daylight,rainy,False,True,afternoon,False,True,1,0.13
1,1,urban,4,0.99,35,daylight,clear,True,False,evening,True,True,0,0.35
2,2,rural,4,0.63,70,dim,clear,False,True,morning,True,False,2,0.30
3,3,highway,4,0.07,35,dim,rainy,True,True,morning,False,False,1,0.21
4,4,rural,1,0.58,60,daylight,foggy,False,False,evening,True,False,1,0.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517749,517749,highway,4,0.10,70,daylight,foggy,True,True,afternoon,False,False,2,0.32
517750,517750,rural,4,0.47,35,daylight,rainy,True,True,morning,False,False,1,0.26
517751,517751,urban,4,0.62,25,daylight,foggy,False,False,afternoon,False,True,0,0.19
517752,517752,highway,3,0.63,25,night,clear,True,False,afternoon,True,True,3,0.51
517753,517753,highway,2,0.31,45,dim,rainy,False,True,afternoon,True,True,2,0.22

In [ ]:
df=df.drop(columns=['id'],axis=1)

###**Data Preprocessing**

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder
from sklearn.preprocessing import MinMaxScaler

In [ ]:
min_max=MinMaxScaler()
min_max

MinMaxScaler()

In [ ]:
cols_for_scaling=['num_lanes','speed_limit','num_reported_accidents']
cols_for_oe=['road_signs_present','public_road','holiday','school_season']
cols_for_ohe=['road_type','lighting','weather','time_of_day']

In [ ]:
order_oe=['False','True']
oe=OrdinalEncoder(categories=order_oe)
ohe=OneHotEncoder()

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

ct1 = ColumnTransformer(transformers=[('binary_oe', OrdinalEncoder(), cols_for_oe),
 ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cols_for_ohe),
                                    ('min_max',MinMaxScaler(),cols_for_scaling)  ], verbose_feature_names_out=False).set_output(transform='pandas')

In [ ]:
ct1

ColumnTransformer(transformers=[('binary_oe', OrdinalEncoder(),
                                 ['road_signs_present', 'public_road',
                                  'holiday', 'school_season']),
                                ('onehot',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['road_type', 'lighting', 'weather',
                                  'time_of_day']),
                                ('min_max', MinMaxScaler(),
                                 ['num_lanes', 'speed_limit',
                                  'num_reported_accidents'])],
                  verbose_feature_names_out=False)

In [ ]:
encoded_cols=ct1.fit_transform(df)
encoded_cols

,road_signs_present,public_road,holiday,school_season,road_type_highway,road_type_rural,road_type_urban,lighting_daylight,lighting_dim,lighting_night,weather_clear,weather_foggy,weather_rainy,time_of_day_afternoon,time_of_day_evening,time_of_day_morning,num_lanes,speed_limit,num_reported_accidents
0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.333333,0.222222,0.142857
1,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.000000,0.222222,0.000000
2,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.000000,1.000000,0.285714
3,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.000000,0.222222,0.142857
4,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.000000,0.777778,0.142857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517749,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.000000,1.000000,0.285714
517750,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.000000,0.222222,0.142857
517751,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.000000,0.000000,0.000000
517752,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.666667,0.000000,0.428571
517753,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.333333,0.444444,0.285714

In [ ]:
numerical_cols=df[['curvature','accident_risk']]
numerical_cols

        curvature  accident_risk
0            0.06           0.13
1            0.99           0.35
2            0.63           0.30
3            0.07           0.21
4            0.58           0.56
...           ...            ...
517749       0.10           0.32
517750       0.47           0.26
517751       0.62           0.19
517752       0.63           0.51
517753       0.31           0.22

[517754 rows x 2 columns]

In [ ]:
X_final = pd.concat([encoded_cols, numerical_cols], axis=1)

In [ ]:
X_final

,road_signs_present,public_road,holiday,school_season,road_type_highway,road_type_rural,road_type_urban,lighting_daylight,lighting_dim,lighting_night,...,weather_foggy,weather_rainy,time_of_day_afternoon,time_of_day_evening,time_of_day_morning,num_lanes,speed_limit,num_reported_accidents,curvature,accident_risk
0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.333333,0.222222,0.142857,0.06,0.13
1,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.000000,0.222222,0.000000,0.99,0.35
2,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.000000,1.000000,0.285714,0.63,0.30
3,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.000000,0.222222,0.142857,0.07,0.21
4,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.000000,0.777778,0.142857,0.58,0.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517749,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.000000,1.000000,0.285714,0.10,0.32
517750,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.000000,0.222222,0.142857,0.47,0.26
517751,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.000000,0.000000,0.000000,0.62,0.19
517752,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.666667,0.000000,0.428571,0.63,0.51
517753,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.333333,0.444444,0.285714,0.31,0.22

In [ ]:
x=X_final.drop(columns=['accident_risk'],axis=1)

In [ ]:
x

,road_signs_present,public_road,holiday,school_season,road_type_highway,road_type_rural,road_type_urban,lighting_daylight,lighting_dim,lighting_night,weather_clear,weather_foggy,weather_rainy,time_of_day_afternoon,time_of_day_evening,time_of_day_morning,num_lanes,speed_limit,num_reported_accidents,curvature
0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.333333,0.222222,0.142857,0.06
1,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.000000,0.222222,0.000000,0.99
2,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.000000,1.000000,0.285714,0.63
3,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.000000,0.222222,0.142857,0.07
4,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.000000,0.777778,0.142857,0.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517749,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.000000,1.000000,0.285714,0.10
517750,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.000000,0.222222,0.142857,0.47
517751,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.000000,0.000000,0.000000,0.62
517752,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.666667,0.000000,0.428571,0.63
517753,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.333333,0.444444,0.285714,0.31

In [ ]:
y=X_final['accident_risk']

In [ ]:
y

0         0.13
1         0.35
2         0.30
3         0.21
4         0.56
          ...
517749    0.32
517750    0.26
517751    0.19
517752    0.51
517753    0.22
Name: accident_risk, Length: 517754, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((414203, 20), (414203,), (103551, 20), (103551,))

# **Model Building**

##**DecisionTreeRegressor**

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
dt=DecisionTreeRegressor()
dt

DecisionTreeRegressor()

In [ ]:
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [ ]:
dt.score(x_train,y_train)

0.9980747381938292

In [ ]:
y_pred=dt.predict(x_test)
y_pred

array([0.17, 0.29, 0.35, ..., 0.46, 0.18, 0.13])

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7490630715148722

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
from sklearn.model_selection import RandomizedSearchCV, KFold
cv = KFold(n_splits=3, shuffle=True, random_state=42)

model = DecisionTreeRegressor(random_state=42)

param_dist = {
    "max_depth": randint(3, 20),
    "min_samples_split": randint(2, 50),
    "min_samples_leaf": randint(1, 30),
    "criterion": ["squared_error"],
}

search = RandomizedSearchCV(
    estimator=model,
    param_distributions=param_dist,
    n_iter=10,                       # number of random trials
    scoring="neg_mean_squared_error",
    cv=cv,
    n_jobs=-1,
    random_state=42,
    verbose=1
)

search.fit(x_train, y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits

RandomizedSearchCV(cv=KFold(n_splits=3, random_state=42, shuffle=True),
                   estimator=DecisionTreeRegressor(random_state=42), n_jobs=-1,
                   param_distributions={'criterion': ['squared_error'],
                                        'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7dac389ecf80>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7dac389ed790>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7dac38d03530>},
                   random_state=42, scoring='neg_mean_squared_error',
                   verbose=1)

In [ ]:
search.best_params_

{'criterion': 'squared_error',
 'max_depth': 9,
 'min_samples_leaf': 20,
 'min_samples_split': 30}

In [ ]:
search.best_score_

np.float64(-0.003193703838025764)

In [ ]:
search.best_estimator_

DecisionTreeRegressor(max_depth=9, min_samples_leaf=20, min_samples_split=30,
                      random_state=42)

In [ ]:
search.best_estimator_

DecisionTreeRegressor(max_depth=9, min_samples_leaf=20, min_samples_split=30,
                      random_state=42)

In [ ]:
dt=DecisionTreeRegressor(**search.best_params_)
dt

DecisionTreeRegressor(max_depth=9, min_samples_leaf=20, min_samples_split=30)

In [ ]:
dt.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=9, min_samples_leaf=20, min_samples_split=30)

In [ ]:
dt.score(x_train,y_train)

0.8861819972178494

In [ ]:
y_pred=dt.predict(x_test)
y_pred

array([0.12953394, 0.32799615, 0.24942187, ..., 0.40426518, 0.14268763,
       0.15618252])

In [ ]:
r2_score(y_test,y_pred)

0.8840068909598495

## **RandomForestRegressor**

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rf=RandomForestRegressor(n_estimators=30)
rf

RandomForestRegressor(n_estimators=30)

In [ ]:
rf.fit(x_train,y_train)

RandomForestRegressor(n_estimators=30)

In [ ]:
rf.score(x_train,y_train)

0.9792995474424178

In [ ]:
y_pred=rf.predict(x_test)
y_pred

array([0.13166667, 0.34766667, 0.31133333, ..., 0.418     , 0.14233333,
       0.159     ])

In [ ]:
r2_score(y_test,y_pred)

0.8692822542633939

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from scipy.stats import randint
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RandomizedSearchCV, KFold
cv = KFold(n_splits=3, shuffle=True, random_state=42)

model = RandomForestRegressor(random_state=42)

param_forest = {
    "n_estimators": randint(2,20),
    'criterion':['squared_error'],
    'max_depth': randint(2,30),
    'min_samples_split' : randint(2,30),
    'min_samples_leaf': randint(2,30),
    }
search=RandomizedSearchCV(estimator=model,
                          param_distributions=param_forest,
                          n_iter=10,
                          scoring="neg_mean_squared_error",
                          cv=cv,
                          n_jobs=-1,
                          random_state=42,
                          verbose=1)
search.fit(x_train,y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits

RandomizedSearchCV(cv=KFold(n_splits=3, random_state=42, shuffle=True),
                   estimator=RandomForestRegressor(random_state=42), n_jobs=-1,
                   param_distributions={'criterion': ['squared_error'],
                                        'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7dac3890d760>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7dac3890d9a0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7dac3890d880>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7dac3890d670>},
                   random_state=42, scoring='neg_mean_squared_error',
                   verbose=1)

In [ ]:
search.best_params_

{'criterion': 'squared_error',
 'max_depth': 9,
 'min_samples_leaf': 22,
 'min_samples_split': 8,
 'n_estimators': 12}

In [ ]:
search.best_estimator_

RandomForestRegressor(max_depth=9, min_samples_leaf=22, min_samples_split=8,
                      n_estimators=12, random_state=42)

In [ ]:
search.best_score_

np.float64(-0.0031806327886720353)

In [ ]:
rf=RandomForestRegressor(**search.best_params_)
rf

RandomForestRegressor(max_depth=9, min_samples_leaf=22, min_samples_split=8,
                      n_estimators=12)

In [ ]:
rf.fit(x_train,y_train)

RandomForestRegressor(max_depth=9, min_samples_leaf=22, min_samples_split=8,
                      n_estimators=12)

In [ ]:
rf.score(x_train,y_train)

0.8865946545147216

In [ ]:
y_pred=rf.predict(x_test)
y_pred

array([0.12870082, 0.33037669, 0.24913447, ..., 0.41224284, 0.14121258,
       0.15466218])

In [ ]:
r2_score(y_test,y_pred)

0.8844208194277177

##**LinearRegressor**

In [ ]:
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.model_selection import RandomizedSearchCV, KFold
from scipy.stats import loguniform

cv = KFold(n_splits=3, shuffle=True, random_state=42)

model_type = "ElasticNet"  # "Ridge", "Lasso", or "ElasticNet"

if model_type == "Ridge":
    model = Ridge()
    param_dist = {
        "alpha": loguniform(1e-4, 1e2)
    }

elif model_type == "Lasso":
    model = Lasso(max_iter=10000)
    param_dist = {
        "alpha": loguniform(1e-4, 1e2)
    }

elif model_type == "ElasticNet":
    model = ElasticNet(max_iter=10000)
    param_dist = {
        "alpha": loguniform(1e-4, 1e2),
        "l1_ratio": [0.1, 0.3, 0.5, 0.7, 0.9]
    }

search = RandomizedSearchCV(
    model,
    param_distributions=param_dist,
    n_iter=20,
    cv=cv,
    scoring="neg_mean_squared_error",
    random_state=42
)

search.fit(x_train, y_train)

RandomizedSearchCV(cv=KFold(n_splits=3, random_state=42, shuffle=True),
                   estimator=ElasticNet(max_iter=10000), n_iter=20,
                   param_distributions={'alpha': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x7dac38aa14f0>,
                                        'l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9]},
                   random_state=42, scoring='neg_mean_squared_error')

In [ ]:
search.best_params_

{'alpha': np.float64(0.00013289448722869195), 'l1_ratio': 0.3}

In [ ]:
search.best_estimator_

ElasticNet(alpha=np.float64(0.00013289448722869195), l1_ratio=0.3,
           max_iter=10000)

In [ ]:
en=ElasticNet(**search.best_params_)
en

ElasticNet(alpha=np.float64(0.00013289448722869195), l1_ratio=0.3)

In [ ]:
en.fit(x_train,y_train)

ElasticNet(alpha=np.float64(0.00013289448722869195), l1_ratio=0.3)

In [ ]:
en.score(x_train,y_train)

0.8051469048316958

In [ ]:
y_pred=en.predict(x_test)
y_pred

array([0.20615355, 0.26828433, 0.20960463, ..., 0.47546813, 0.12332198,
       0.22788027])

In [ ]:
r2_score(y_test,y_pred)

0.8041833888945671

##**Saving the Best Model for Deployment**

#### **I want to use RandomForest Model for Deployment because it's Training and Testing Scores are very high as compared to other models**

In [ ]:
import pickle

# 1. Create model
rf = rf.fit(x_train,y_train)


# 2. Save the FITTED model
with open("rf.pkl", "wb") as file:
    pickle.dump(rf, file)


from google.colab import files
files.download("rf.pkl")